site_name: CppPrimer学习笔记

copyright: 'Copyright &copy; 2018 Diwen Liu'

docs_dir: study_notes

repo_url: https://github.com/demon90s/CppPrimer
edit_uri: "tree/master/study_notes"

pages:
  - Home: index.md
  - Chapters: 
    - ch01 开始: ch01 开始.md
    - ch02 变量和基本类型:
      - 变量和基本类型1: ch02 变量和基本类型_1.md
      - 变量和基本类型2: ch02 变量和基本类型_2.md
    - ch03 字符串、向量和数组: ch03 字符串、向量和数组.md
    - ch04 表达式: ch04 表达式.md
    - ch05 语句: ch05 语句.md
    - ch06 函数:
      - 函数1: ch06 函数_1.md
      - 函数2: ch06 函数_2.md
    - ch07 类: ch07 类.md
    - ch08 IO库: ch08 IO库.md
    - ch09 顺序容器: ch09 顺序容器.md
    - ch10 泛型算法: ch10 泛型算法.md
    - ch11 关联容器: ch11 关联容器.md
    - ch12 动态内存: ch12 动态内存.md
    - ch13 拷贝控制:
      - 拷贝控制1: ch13 拷贝控制_1.md
      - 拷贝控制2: ch13 拷贝控制_2.md
    - ch14 操作重载与类型转换: ch14 操作重载与类型转换.md
    - ch15 面向对象程序设计: ch15 面向对象程序设计.md
  - CheatSheet:
    - static的3个用途: cheatsheet/static的3个用途.md
    - 若干种typedef: cheatsheet/若干种typedef.md
    - 类内初始值: cheatsheet/类内初始值.md

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  font:
    text: 'Raleway Bold'
    code: 'Ubuntu Mono'

extra:
  search:
    language: 'jp'