site_name: C++ Study Note
site_description: C++ Study Note

copyright: 'Copyright &copy; 2018 Diwen Liu'

docs_dir: study_notes

repo_url: https://github.com/demon90s/CppStudy
edit_uri: "tree/master/study_notes"

pages:
  - Introduction: index.md
  - C++ Primer:
    - Chapters: 
      - ch01 开始: CppPrimer/ch01 开始.md
      - ch02 变量和基本类型: CppPrimer/ch02 变量和基本类型.md
      - ch03 字符串、向量和数组: CppPrimer/ch03 字符串、向量和数组.md
      - ch04 表达式: CppPrimer/ch04 表达式.md
      - ch05 语句: CppPrimer/ch05 语句.md
      - ch06 函数: CppPrimer/ch06 函数.md
      - ch07 类: CppPrimer/ch07 类.md
      - ch08 IO库: CppPrimer/ch08 IO库.md
      - ch09 顺序容器: CppPrimer/ch09 顺序容器.md
      - ch10 泛型算法: CppPrimer/ch10 泛型算法.md
      - ch11 关联容器: CppPrimer/ch11 关联容器.md
      - ch12 动态内存: CppPrimer/ch12 动态内存.md
      - ch13 拷贝控制: CppPrimer/ch13 拷贝控制.md
      - ch14 操作重载与类型转换: CppPrimer/ch14 操作重载与类型转换.md
      - ch15 面向对象程序设计: CppPrimer/ch15 面向对象程序设计.md
      - ch16 模板与泛型编程: CppPrimer/ch16 模板与泛型编程.md
      - ch17 标准库特殊设施: CppPrimer/ch17 标准库特殊设施.md
      - ch18 用于大型程序的工具: CppPrimer/ch18 用于大型程序的工具.md
      - ch19 特殊工具与技术: CppPrimer/ch19 特殊工具与技术.md
    - CheatSheet:
      - static的3个用途: CppPrimer/cheatsheet/static的3个用途.md
      - 若干种typedef: CppPrimer/cheatsheet/若干种typedef.md
      - 类内初始值: CppPrimer/cheatsheet/类内初始值.md
      - 运算符重载: CppPrimer/cheatsheet/运算符重载.md
      - 向set中插入自定义类型对象: CppPrimer/cheatsheet/向set中插入自定义类型对象.md

  - Effective C++:
    - 1 让自己习惯C++: 
      - 条款01：视C++为一个语言联邦: EffectiveCpp/1 让自己习惯C++/条款01：视C++为一个语言联邦.md
      - 条款02：尽量以const, enum, inline替换#define: EffectiveCpp/1 让自己习惯C++/条款02：尽量以const, enum, inline替换#define.md
      - 条款03：尽可能使用const: EffectiveCpp/1 让自己习惯C++/条款03：尽可能使用const.md
      - 条款04：确定对象被使用前已被初始化: EffectiveCpp/1 让自己习惯C++/条款04：确定对象被使用前已被初始化.md
    - 2 构造、析构、赋值运算:
      - 条款05：了解C++默默编写并调用哪些函数: EffectiveCpp/2 构造、析构、赋值运算/条款05：了解C++默默编写并调用哪些函数.md
      - 条款06：若不想使用编译器自动生成的函数，就该明确拒绝: EffectiveCpp/2 构造、析构、赋值运算/条款06：若不想使用编译器自动生成的函数，就该明确拒绝.md

theme:
  name: 'material'
  logo:
    icon: 'school'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  font:
    text: 'Open Sans'
    code: 'Open Sans Mono'
  language: 'zh'
  feature:
    tabs: true

extra:
  search:
    language: 'en, jp'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'